In [2]:
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
pd.set_option("display.max_rows", None, "display.max_columns", None)
df = DataFrame()
df['Permimeter'] = [226.2792,226.1302,225.0661,224.9662,228.1638,227.6332,226.6487,228.1454,226.559,226.7598,225.0664,226.9391,224.7138,224.2611,227.4165,227.0428,225.0983,226.0314,227.1495,226.7765,224.6379,224.8460,224.0050,226.0908,226.4424,224.7993,227.3342,224.0896,224.5984,228.7606,228.8793,224.1546,226.4694,228.3136,225.2144,228.1714,228.0680,227.1449,224.0112,225.8986,228.5220,227.4018,225.8941,227.1598,225.2163,226.8571,228.9086,228.2484,225.4172,227.4123,224.6881,229.3530,232.3500,232.1404,226.6513,224.0732,231.0762,226.7186,233.7895,228.4325,230.2635,226.9621,232.1271,233.9571,230.0394,227.9592,233.5476,230.0190,227.8258,225.9030,231.6112,230.5740,225.2735,227.2936,232.3394,226.6419,231.7998,231.9482,234.9328,230.8782,230.1937,231.6527,231.8005,232.3323,224.6965,225.5379,230.6305,229.7264,228.7850,229.6142,232.0321,224.1129,232.9796,225.5218,234.6410,231.3485,226.7638,227.9120,233.1384,224.5257]
df['Weight'] = [161.4935,162.8079,161.1678,160.3514,160.7213,162.0547,162.5178,162.9104,160.6455,162.2810,161.7523,161.2089,161.5301,161.4869,161.9541,162.2311,160.9059,160.2688,162.4779,161.1688,162.3259,160.5381,160.3281,162.7155,162.6291,162.9994,162.5928,160.1106,161.6340,162.9928,161.5330,162.6205,160.2107,162.9626,162.7681,161.6928,161.2944,161.0135,162.1622,160.0410,161.1222,162.7681,161.6394,161.4217,161.4896,160.9269,162.8525,162.9460,161.5407,162.9778,162.0865,161.5028,162.1571,162.8310,162.7912,161.9650,161.8855,161.6235,161.1106,162.5076,161.2639,161.7118,161.7917,162.7710,161.0425,162.6882,161.5761,161.5007,161.9768,162.4581,161.4052,161.4326,162.9527,162.1865,161.6088,162.9354,162.7919,161.3801,161.0036,162.4235,162.7355,161.2366,161.0780,162.1964,162.2086,162.0329,161.0150,162.3779,162.8920,162.7471,161.2266,161.7091,161.4839,162.1207,162.2255,161.6016,162.5963,162.5913,162.5622,161.7022 ]
df['Elasticity'] = [0.5736,0.5799,0.5708,0.5725,0.5781,0.5708,0.5753,0.5780,0.5774,0.5714,0.5744,0.5735,0.5748,0.5759,0.5715,0.5791,0.5764,0.5716,0.5757,0.5793,0.5778,0.5769,0.5747,0.5726,0.5757,0.5725,0.5732,0.5791,0.5789,0.5779,0.5793,0.5718,0.5752,0.5763,0.5791,0.5766,0.5739,0.5774,0.5782,0.5760,0.5708,0.5792,0.5705,0.5753,0.5712,0.5738,0.5781,0.5724,0.5788,0.5771,0.5205,0.5271,0.5299,0.5216,0.5211,0.5291,0.5248,0.5285,0.5281,0.5219,0.5225,0.5205,0.5261,0.5278,0.5251,0.5203,0.5299,0.5250,0.5233,0.5217,0.5263,0.5258 ,0.5275,0.5215,0.5236,0.5214,0.5285,0.5234,0.5228,0.5201,0.5280,0.5250,0.5254,0.5287,0.5272,0.5267,0.5218,0.5255,0.5296,0.5260,0.5281,0.5298,0.5289,0.5221,0.5203,0.5245,0.5201,0.5247,0.5295,0.5225]
df['Type_of_Ball'] = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
df

Permimeter    Weight  Elasticity  Type_of_Ball
0     226.2792  161.4935      0.5736             0
1     226.1302  162.8079      0.5799             0
2     225.0661  161.1678      0.5708             0
3     224.9662  160.3514      0.5725             0
4     228.1638  160.7213      0.5781             0
5     227.6332  162.0547      0.5708             0
6     226.6487  162.5178      0.5753             0
7     228.1454  162.9104      0.5780             0
8     226.5590  160.6455      0.5774             0
9     226.7598  162.2810      0.5714             0
10    225.0664  161.7523      0.5744             0
11    226.9391  161.2089      0.5735             0
12    224.7138  161.5301      0.5748             0
13    224.2611  161.4869      0.5759             0
14    227.4165  161.9541      0.5715             0
15    227.0428  162.2311      0.5791             0
16    225.0983  160.9059      0.5764             0
17    226.0314  160.2688      0.5716             0
18    227.1495  162.4779      0.5757             0
19    226.7765  161.1688      0.5793             0
20    224.6379  162.3259      0.5778             0
21    224.8460  160.5381      0.5769             0
22    224.0050  160.3281      0.5747             0
23    226.0908  162.7155      0.5726             0
24    226.4424  162.6291      0.5757             0
25    224.7993  162.9994      0.5725             0
26    227.3342  162.5928      0.5732             0
27    224.0896  160.1106      0.5791             0
28    224.5984  161.6340      0.5789             0
29    228.7606  162.9928      0.5779             0
30    228.8793  161.5330      0.5793             0
31    224.1546  162.6205      0.5718             0
32    226.4694  160.2107      0.5752             0
33    228.3136  162.9626      0.5763             0
34    225.2144  162.7681      0.5791             0
35    228.1714  161.6928      0.5766             0
36    228.0680  161.2944      0.5739             0
37    227.1449  161.0135      0.5774             0
38    224.0112  162.1622      0.5782             0
39    225.8986  160.0410      0.5760             0
40    228.5220  161.1222      0.5708             0
41    227.4018  162.7681      0.5792             0
42    225.8941  161.6394      0.5705             0
43    227.1598  161.4217      0.5753             0
44    225.2163  161.4896      0.5712             0
45    226.8571  160.9269      0.5738             0
46    228.9086  162.8525      0.5781             0
47    228.2484  162.9460      0.5724             0
48    225.4172  161.5407      0.5788             0
49    227.4123  162.9778      0.5771             0
50    224.6881  162.0865      0.5205             1
51    229.3530  161.5028      0.5271             1
52    232.3500  162.1571      0.5299             1
53    232.1404  162.8310      0.5216             1
54    226.6513  162.7912      0.5211             1
55    224.0732  161.9650      0.5291             1
56    231.0762  161.8855      0.5248             1
57    226.7186  161.6235      0.5285             1
58    233.7895  161.1106      0.5281             1
59    228.4325  162.5076      0.5219             1
60    230.2635  161.2639      0.5225             1
61    226.9621  161.7118      0.5205             1
62    232.1271  161.7917      0.5261             1
63    233.9571  162.7710      0.5278             1
64    230.0394  161.0425      0.5251             1
65    227.9592  162.6882      0.5203             1
66    233.5476  161.5761      0.5299             1
67    230.0190  161.5007      0.5250             1
68    227.8258  161.9768      0.5233             1
69    225.9030  162.4581      0.5217             1
70    231.6112  161.4052      0.5263             1
71    230.5740  161.4326      0.5258             1
72    225.2735  162.9527      0.5275             1
73    227.2936  162.1865      0.5215             1
74    232.3394  161.6088      0.5236             1
75    226.6419  162.9354      0.5214             1
76    231.7998  162.7919      0.5285             1
77    231.9482  161.3801  

# Deliverable 4 Task 2

In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

# Dividing Data into Training Set and Test Set

In [4]:
dfX = df.drop(columns=['Type_of_Ball'])
sy = df.Type_of_Ball
from sklearn.model_selection import train_test_split
dfX_train, dfX_test,sy_train,sy_test = train_test_split(dfX,sy)
dfX_train, dfX_test,sy_train,sy_test

(    Permimeter    Weight  Elasticity
 31    224.1546  162.6205      0.5718
 73    227.2936  162.1865      0.5215
 22    224.0050  160.3281      0.5747
 67    230.0190  161.5007      0.5250
 90    232.0321  161.2266      0.5281
 25    224.7993  162.9994      0.5725
 79    230.8782  162.4235      0.5201
 49    227.4123  162.9778      0.5771
 6     226.6487  162.5178      0.5753
 81    231.6527  161.2366      0.5250
 66    233.5476  161.5761      0.5299
 15    227.0428  162.2311      0.5791
 62    232.1271  161.7917      0.5261
 3     224.9662  160.3514      0.5725
 8     226.5590  160.6455      0.5774
 12    224.7138  161.5301      0.5748
 48    225.4172  161.5407      0.5788
 84    224.6965  162.2086      0.5272
 92    232.9796  161.4839      0.5289
 51    229.3530  161.5028      0.5271
 24    226.4424  162.6291      0.5757
 5     227.6332  162.0547      0.5708
 57    226.7186  161.6235      0.5285
 16    225.0983  160.9059      0.5764
 41    227.4018  162.7681      0.5792
 19    226.7

# Data Preprocessing

### a) with LabelEncoder()

In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le = le.fit(sy_train)
y_train = le.transform(sy_train)
sy_train,y_train

(31    0
 73    1
 22    0
 67    1
 90    1
 25    0
 79    1
 49    0
 6     0
 81    1
 66    1
 15    0
 62    1
 3     0
 8     0
 12    0
 48    0
 84    1
 92    1
 51    1
 24    0
 5     0
 57    1
 16    0
 41    0
 19    0
 20    0
 28    0
 7     0
 23    0
 53    1
 54    1
 50    1
 98    1
 35    0
 78    1
 56    1
 26    0
 71    1
 0     0
 29    0
 42    0
 70    1
 95    1
 10    0
 60    1
 88    1
 75    1
 86    1
 87    1
 30    0
 4     0
 44    0
 89    1
 37    0
 63    1
 18    0
 39    0
 27    0
 33    0
 40    0
 46    0
 13    0
 21    0
 17    0
 47    0
 99    1
 94    1
 80    1
 93    1
 69    1
 97    1
 1     0
 85    1
 38    0
 Name: Type_of_Ball, dtype: int64,
 array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64))

### b) Processing attributes with StandardScaler()

In [6]:
dfX_train.to_numpy()

array([[224.1546, 162.6205,   0.5718],
       [227.2936, 162.1865,   0.5215],
       [224.005 , 160.3281,   0.5747],
       [230.019 , 161.5007,   0.525 ],
       [232.0321, 161.2266,   0.5281],
       [224.7993, 162.9994,   0.5725],
       [230.8782, 162.4235,   0.5201],
       [227.4123, 162.9778,   0.5771],
       [226.6487, 162.5178,   0.5753],
       [231.6527, 161.2366,   0.525 ],
       [233.5476, 161.5761,   0.5299],
       [227.0428, 162.2311,   0.5791],
       [232.1271, 161.7917,   0.5261],
       [224.9662, 160.3514,   0.5725],
       [226.559 , 160.6455,   0.5774],
       [224.7138, 161.5301,   0.5748],
       [225.4172, 161.5407,   0.5788],
       [224.6965, 162.2086,   0.5272],
       [232.9796, 161.4839,   0.5289],
       [229.353 , 161.5028,   0.5271],
       [226.4424, 162.6291,   0.5757],
       [227.6332, 162.0547,   0.5708],
       [226.7186, 161.6235,   0.5285],
       [225.0983, 160.9059,   0.5764],
       [227.4018, 162.7681,   0.5792],
       [226.7765, 161.168

In [7]:
n1 = preprocessing.StandardScaler()
n1 = n1.fit(dfX_train.to_numpy())
X_train = n1.transform (dfX_train.to_numpy())
X_train

array([[-1.30310321,  0.91474853,  0.74985511],
       [-0.20580971,  0.37097728, -1.22241596],
       [-1.35539856, -1.95746623,  0.86356457],
       [ 0.74690253, -0.48828152, -1.0851804 ],
       [ 1.45061759, -0.8317094 , -0.9636289 ],
       [-1.07773682,  1.38948338,  0.77730222],
       [ 1.04725124,  0.66792149, -1.27731019],
       [-0.164316  ,  1.36242011,  0.95766896],
       [-0.43124602,  0.78607271,  0.88709067],
       [ 1.31799154, -0.81918011, -1.0851804 ],
       [ 1.98038768, -0.39381066, -0.89305061],
       [-0.29348133,  0.42685792,  1.03608928],
       [ 1.48382653, -0.12367914, -1.04204922],
       [-1.01939394, -1.92827298,  0.77730222],
       [-0.46260226, -1.55978652,  0.96943201],
       [-1.10762487, -0.4514454 ,  0.86748559],
       [-0.86173884, -0.43816435,  1.02432623],
       [-1.11367239,  0.39866702, -0.99891805],
       [ 1.78183313, -0.50933073, -0.93226077],
       [ 0.51409034, -0.48565037, -1.00283906],
       [-0.50336187,  0.92552372,  0.902

# Building Machine Learning Model for Classification

In [8]:
X_train.shape

(75, 3)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)
knn

KNeighborsClassifier(n_neighbors=1)

# Evaluation of the model

In [10]:
y_test = le.transform(sy_test.to_numpy())
sy_test, y_test

(74    1
 96    1
 9     0
 45    0
 83    1
 76    1
 65    1
 55    1
 2     0
 72    1
 61    1
 52    1
 77    1
 58    1
 32    0
 82    1
 59    1
 43    0
 91    1
 64    1
 36    0
 34    0
 11    0
 14    0
 68    1
 Name: Type_of_Ball, dtype: int64,
 array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        0, 0, 1], dtype=int64))

In [11]:
X_test = n1.transform(dfX_test.to_numpy())
dfX_test, X_test

(    Permimeter    Weight  Elasticity
 74    232.3394  161.6088      0.5236
 96    226.7638  162.5963      0.5201
 9     226.7598  162.2810      0.5714
 45    226.8571  160.9269      0.5738
 83    232.3323  162.1964      0.5287
 76    231.7998  162.7919      0.5285
 65    227.9592  162.6882      0.5203
 55    224.0732  161.9650      0.5291
 2     225.0661  161.1678      0.5708
 72    225.2735  162.9527      0.5275
 61    226.9621  161.7118      0.5205
 52    232.3500  162.1571      0.5299
 77    231.9482  161.3801      0.5234
 58    233.7895  161.1106      0.5281
 32    226.4694  160.2107      0.5752
 82    231.8005  161.0780      0.5254
 59    228.4325  162.5076      0.5219
 43    227.1598  161.4217      0.5753
 91    224.1129  161.7091      0.5298
 64    230.0394  161.0425      0.5251
 36    228.0680  161.2944      0.5739
 34    225.2144  162.7681      0.5791
 11    226.9391  161.2089      0.5735
 14    227.4165  161.9541      0.5715
 68    227.8258  161.9768      0.5233,
 array([[ 1

# Predicting the class

In [12]:
knn.predict(X_test)

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1], dtype=int64)

In [13]:
y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1], dtype=int64)

In [14]:
knn.score(X_test, y_test)

1.0

In [15]:
knn.score(X_train, y_train)

1.0

# Task 3

In [17]:
import sklearn
y_true = knn.predict(X_test)
y_pred = y_test
sklearn.metrics.confusion_matrix(y_true, y_pred)

array([[ 9,  0],
       [ 0, 16]], dtype=int64)

# Task 4

In [19]:
new_example_rawdata  = np.array([[236.2993,159.4835,0.5831]])
X_new = n1.transform(new_example_rawdata)
X_new

array([[ 2.94229355, -3.01569018,  1.19292992]])

In [20]:
knn.predict(X_new)

array([1], dtype=int64)