In [89]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Classification of Apples
##### The mass,width, height,quality index and the freshness of the apples in a crate are given. the average mass,width,height,quality index are given as 97.5, 8.28,7.1 and  5 respectively. Predict if the apple is fresh or rotten. 

In [90]:
df = DataFrame()

df['Mass'] = ['129','50','100','120','70','85','99','67','78','130','131','111']
df['width'] = ['8.4','7.7','8.0','6.8','9.9','8.6','7.0','7.8','9.2','8.1','8.9','9.0']
df['height'] = ['7.4','6.3','5.0','8.0','7.8','7.0','6.8','6.6','7.2','8.8','7.6','6.7']
df['quality index'] = ['2.0','3.0','7.0','1.0','9.0','10.0','2.0','3.0','6.0','4.0','8.0','1.0']
df['Fresh_or_Rotten'] = ['F','F','F','R','F','R','R','F','F','R','F','R']

# Dividing data

In [91]:
dfX = df.drop(columns=['Fresh_or_Rotten'])
sy = df.Fresh_or_Rotten
from sklearn.model_selection import train_test_split
dfX_train, dfX_test,sy_train,sy_test = train_test_split(dfX,sy)

# Data preprocessing
#### A. with LabelEncoder()

In [92]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le = le.fit(sy_train)
y_train = le.transform(sy_train)
sy_train,y_train

(2     F
 8     F
 11    R
 7     F
 1     F
 10    F
 0     F
 6     R
 4     F
 Name: Fresh_or_Rotten, dtype: object,
 array([0, 0, 1, 0, 0, 0, 0, 1, 0]))

#### A. with MinMaxScaler()

In [93]:
dfX_train.to_numpy()

array([['100', '8.0', '5.0', '7.0'],
       ['78', '9.2', '7.2', '6.0'],
       ['111', '9.0', '6.7', '1.0'],
       ['67', '7.8', '6.6', '3.0'],
       ['50', '7.7', '6.3', '3.0'],
       ['131', '8.9', '7.6', '8.0'],
       ['129', '8.4', '7.4', '2.0'],
       ['99', '7.0', '6.8', '2.0'],
       ['70', '9.9', '7.8', '9.0']], dtype=object)

In [94]:
n1 = preprocessing.MinMaxScaler()
n1 =n1.fit(dfX_train.to_numpy())
X_train = n1.transform(dfX_train.to_numpy())
X_train

array([[0.61728395, 0.34482759, 0.        , 0.75      ],
       [0.34567901, 0.75862069, 0.78571429, 0.625     ],
       [0.75308642, 0.68965517, 0.60714286, 0.        ],
       [0.20987654, 0.27586207, 0.57142857, 0.25      ],
       [0.        , 0.24137931, 0.46428571, 0.25      ],
       [1.        , 0.65517241, 0.92857143, 0.875     ],
       [0.97530864, 0.48275862, 0.85714286, 0.125     ],
       [0.60493827, 0.        , 0.64285714, 0.125     ],
       [0.24691358, 1.        , 1.        , 1.        ]])

# Building the machine learning model for classification

In [95]:
X_train.shape

(9, 4)

In [96]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 9)
knn = knn.fit(X_train,y_train)
knn

KNeighborsClassifier(n_neighbors=9)

# Evaluation of model using test sets

## Preprocessing the datasets of dfX_test and sy_test

In [97]:
y_test = le.transform(sy_test.to_numpy())
sy_test,y_test

(3    R
 9    R
 5    R
 Name: Fresh_or_Rotten, dtype: object,
 array([1, 1, 1]))

In [98]:
X_test = n1.transform(dfX_test.to_numpy())
dfX_test,X_test

(  Mass width height quality index
 3  120   6.8    8.0           1.0
 9  130   8.1    8.8           4.0
 5   85   8.6    7.0          10.0,
 array([[ 0.86419753, -0.06896552,  1.07142857,  0.        ],
        [ 0.98765432,  0.37931034,  1.35714286,  0.375     ],
        [ 0.43209877,  0.55172414,  0.71428571,  1.125     ]]))

## Apply model to predict the class of X_test and compare with y_test

In [99]:
knn.predict(X_test)

array([0, 0, 0])

In [100]:
y_test

array([1, 1, 1])

In [101]:
knn.score(X_test,y_test)

0.0

In [102]:
knn.score(X_train,y_train)

0.7777777777777778

# Application of the model for the prediction (classification of new example)

In [103]:
new_example_rawdata  = np.array([[97.5,8.28,7.1,5]])
X_new = n1.transform(new_example_rawdata)
X_new

array([[0.58641975, 0.44137931, 0.75      , 0.5       ]])

In [104]:
knn.predict(X_new)

array([0])

In [105]:
le.inverse_transform(knn.predict(X_new))

array(['F'], dtype=object)

#### Number of instances: 12
#### Number of attributes: 4
#### list of attributes: Mass, width, height,quality index
#### list of classes: F,R
#### Creator: Farica Mago